services:
  db:
    build:
      context: .docker/postgis-18
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mercado-facil
    ports:
      - 5432:5432
